name: Enforce Branch Creation Policy

on:
  create:

jobs:
  enforce-branch-policy:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if branch creator is in the allowed team
        id: check_user
        run: |
          ORG_NAME="your_organization"  # Change this to your GitHub organization name
          TEAM_SLUG="allowed"  # Change this to your team slug
          MEMBER_LOGIN_IDS=$(gh api /orgs/$ORG_NAME/teams/$TEAM_SLUG/members --jq '.[].login' | tr '\n' ' ')
          echo "Team members: $MEMBER_LOGIN_IDS"
          if [[ $MEMBER_LOGIN_IDS =~ (^|[[:space:]])"${{ github.actor }}"($|[[:space:]]) ]]; then
            echo "User is allowed to create branches."
            echo "::set-output name=is_allowed::true"
          else
            echo "User is not allowed to create branches."
            echo "::set-output name=is_allowed::false"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete unauthorized branch
        if: steps.check_user.outputs.is_allowed == 'false'
        run: |
          echo "Deleting unauthorized branch created by ${{ github.actor }}"
          gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
